In [1]:
import sqlite3

In [2]:
import pandas as pd

In [3]:
con = sqlite3.connect('sakila.db')

In [4]:
def sql_to_df(sql_query):
    df = pd.read_sql(sql_query, con)
    return df

In [5]:
query = '''select first_name, last_name
                    from  customer'''
sql_to_df(query)

    first_name  last_name
0         MARY      SMITH
1     PATRICIA    JOHNSON
2        LINDA   WILLIAMS
3      BARBARA      JONES
4    ELIZABETH      BROWN
5     JENNIFER      DAVIS
6        MARIA     MILLER
7        SUSAN     WILSON
8     MARGARET      MOORE
9      DOROTHY     TAYLOR
10        LISA   ANDERSON
11       NANCY     THOMAS
12       KAREN    JACKSON
13       BETTY      WHITE
14       HELEN     HARRIS
15      SANDRA     MARTIN
16       DONNA   THOMPSON
17       CAROL     GARCIA
18        RUTH   MARTINEZ
19      SHARON   ROBINSON
20    MICHELLE      CLARK
21       LAURA  RODRIGUEZ
22       SARAH      LEWIS
23    KIMBERLY        LEE
24     DEBORAH     WALKER
25     JESSICA       HALL
26     SHIRLEY      ALLEN
27     CYNTHIA      YOUNG
28      ANGELA  HERNANDEZ
29     MELISSA       KING
..         ...        ...
569       IVAN   CROMWELL
570    JOHNNIE   CHISHOLM
571     SIDNEY   BURLESON
572      BYRON        BOX
573     JULIAN       VEST
574      ISAAC    OGLESBY
575     MORRIS   MCCARTER
576    CLIFTON    MALCOLM
577    WILLARD    LUMPKIN
578      DARYL      LARUE
579       ROSS       GREY
580     VIRGIL    WOFFORD
581       ANDY    VANHORN
582   MARSHALL      THORN
583   SALVADOR       TEEL
584      PERRY   SWAFFORD
585       KIRK    STCLAIR
586     SERGIO  STANFIELD
587     MARION     OCAMPO
588      TRACY   HERRMANN
589       SETH     HANNON
590       KENT  ARSENAULT
591   TERRANCE      ROUSH
592       RENE  MCALISTER
593    EDUARDO      HIATT
594   TERRENCE  GUNDERSON
595    ENRIQUE   FORSYTHE
596    FREDDIE     DUGGAN
597       WADE   DELVALLE
598     AUSTIN    CINTRON

[599 rows x 2 columns]

In [6]:
query = 'select * from customer'
sql_to_df(query)

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
5,6,2,JENNIFER,DAVIS,JENNIFER.DAVIS@sakilacustomer.org,10,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
6,7,1,MARIA,MILLER,MARIA.MILLER@sakilacustomer.org,11,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
7,8,2,SUSAN,WILSON,SUSAN.WILSON@sakilacustomer.org,12,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
8,9,2,MARGARET,MOORE,MARGARET.MOORE@sakilacustomer.org,13,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
9,10,1,DOROTHY,TAYLOR,DOROTHY.TAYLOR@sakilacustomer.org,14,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
10,11,2,LISA,ANDERSON,LISA.ANDERSON@sakilacustomer.org,15,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
11,12,1,NANCY,THOMAS,NANCY.THOMAS@sakilacustomer.org,16,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
12,13,2,KAREN,JACKSON,KAREN.JACKSON@sakilacustomer.org,17,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
13,14,2,BETTY,WHITE,BETTY.WHITE@sakilacustomer.org,18,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
14,15,1,HELEN,HARRIS,HELEN.HARRIS@sakilacustomer.org,19,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
15,16,2,SANDRA,MARTIN,SANDRA.MARTIN@sakilacustomer.org,20,0,2006-02-14 22:04:36.000,2011-09-14 18:10:28
16,17,1,DONNA,THOMPSON,DONNA.THOMPSON@sakilacustomer.org,21,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
17,18,2,CAROL,GARCIA,CAROL.GARCIA@sakilacustomer.org,22,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
18,19,1,RUTH,MARTINEZ,RUTH.MARTINEZ@sakilacustomer.org,23,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
19,20,2,SHARON,ROBINSON,SHARON.ROBINSON@sakilacustomer.org,24,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
20,21,1,MICHELLE,CLARK,MICHELLE.CLARK@sakilacustomer.org,25,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
21,22,1,LAURA,RODRIGUEZ,LAURA.RODRIGUEZ@sakilacustomer.org,26,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
22,23,2,SARAH,LEWIS,SARAH.LEWIS@sakilacustomer.org,27,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
23,24,2,KIMBERLY,LEE,KIMBERLY.LEE@sakilacustomer.org,28,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
24,25,1,DEBORAH,WALKER,DEBORAH.WALKER@sakilacustomer.org,29,1,2006-02-14 22:04:36.000,2011-09-14 18:10:29
25,26,2,JESSICA,HALL,JESSICA.HALL@sakilacustomer.org,30,1,2006-02-14 22:04:36.000,2011-09-14 18:10:29
26,27,2,SHIRLEY,ALLEN,SHIRLEY.ALLEN@sakilacustomer.org,31,1,2006-02-14 22:04:36.000,2011-09-14 18:10:29
27,28,1,CYNTHIA,YOUNG,CYNTHIA.YOUNG@sakilacustomer.org,32,1,2006-02-14 22:04:36.000,2011-09-14 18:10:29
28,29,2,ANGELA,HERNANDEZ,ANGELA.HERNANDEZ@sakilacustomer.org,33,1,2006-02-14 22:04:36.000,2011-09-14 18:10:29
29,30,1,MELISSA,KING,MELISSA.KING@sakilacustomer.org,34,1,2006-02-14 22:04:36.000,2011-09-14 18:10:29
...,...,...,...,...,...,...,...,...,...
569,570,2,IVAN,CROMWELL,IVAN.CROMWELL@sakilacustomer.org,576,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
570,571,2,JOHNNIE,CHISHOLM,JOHNNIE.CHISHOLM@sakilacustomer.org,577,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
571,572,1,SIDNEY,BURLESON,SIDNEY.BURLESON@sakilacustomer.org,578,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
572,573,1,BYRON,BOX,BYRON.BOX@sakilacustomer.org,579,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
573,574,2,JULIAN,VEST,JULIAN.VEST@sakilacustomer.org,580,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
574,575,2,ISAAC,OGLESBY,ISAAC.OGLESBY@sakilacustomer.org,581,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
575,576,2,MORRIS,MCCARTER,MORRIS.MCCARTER@sakilacustomer.org,582,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
576,577,2,CLIFTON,MALCOLM,CLIFTON.MALCOLM@sakilacustomer.org,583,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
577,578,2,WILLARD,LUMPKIN,WILLARD.LUMPKIN@sakilacustomer.org,584,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
578,579,2,DARYL,LARUE,DARYL.LARUE@sakilacustomer.org,585,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
579,580,1,ROSS,GREY,ROSS.GREY@sakilacustomer.org,586,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
580,581,1,VIRGIL,WOFFORD,VIRGIL.WOFFORD@sakilacustomer.org,587,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
581,582,2,ANDY,VANHORN,ANDY.VANHORN@sakilacustomer.org,588,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
582,583,1,MARSHALL,THORN,MARSHALL.THORN@sakilacustomer.org,589,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
583,584,2,SALVADOR,TEEL,SALVADOR.TEEL@sakilacustomer.org,590,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
584,585,1,PERRY,SWAFFORD,PERRY.SWAFFORD@sakilacustomer.org,591,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
585,586,1,KIRK,STCLAIR,KIRK.STCLAIR@sakilacustomer.org,592,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
586,587,1,SERGIO,STANFIELD,SERGIO.STANFIELD@sakilacustomer.org,593,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
587,588,1,MARION,OCAMPO,MARION.OCAMPO@sakilacustomer.org,594,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
588,589,1,TRACY,HERRMANN,TRACY.HERRMANN@sakilacustomer.org,595,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
589,590,2,SETH,HANNON,SETH.HANNON@sakilacustomer.org,596,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
590,591,1,KENT,ARSENAULT,KENT.ARSENAULT@sakilacustomer.org,597,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
591,592,1,TERRANCE,ROUSH,TERRANCE.ROUSH@sakilacustomer.org,598,0,2006-02-14 22:04:37.000,2011-09-14 18:10:44
592,593,2,RENE,MCALISTER,RENE.MCALISTER@sakilacustomer.org,599,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
593,594,1,EDUARDO,HIATT,EDUARDO.HIATT@sakilacustomer.org,600,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,1,2006-02-14 22:04:37.000,2011-09-14 18:10:44

In [7]:
sql_to_df('select country_id from city')

     country_id
0             1
1             2
2             2
3             2
4             3
5             4
6             4
7             5
8             6
9             6
10            6
11            6
12            6
13            6
14            6
15            6
16            6
17            6
18            6
19            6
20            6
21            7
22            8
23            9
24            9
25            9
26           10
27           10
28           11
29           12
..          ...
570         103
571         103
572         103
573         103
574         103
575         103
576         103
577         103
578         103
579         104
580         104
581         104
582         104
583         104
584         104
585         104
586         105
587         105
588         105
589         105
590         105
591         105
592         106
593         107
594         107
595         107
596         107
597         108
598         108
599         109

[600 rows x 1 columns]

In [8]:
sql_to_df('select distinct(country_id) from city')

     country_id
0             1
1             2
2             3
3             4
4             5
5             6
6             7
7             8
8             9
9            10
10           11
11           12
12           13
13           14
14           15
15           16
16           17
17           18
18           19
19           20
20           21
21           22
22           23
23           24
24           25
25           26
26           27
27           28
28           29
29           30
..          ...
79           80
80           81
81           82
82           83
83           84
84           85
85           86
86           87
87           88
88           89
89           90
90           91
91           92
92           93
93           94
94           95
95           96
96           97
97           98
98           99
99          100
100         101
101         102
102         103
103         104
104         105
105         106
106         107
107         108
108         109

[109 rows x 1 columns]

In [11]:
query = '''select * 
                    from customer
                    where store_id = 1'''
sql_to_df(query).head()

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
3,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28
4,7,1,MARIA,MILLER,MARIA.MILLER@sakilacustomer.org,11,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28

In [12]:
query = '''select * 
                    from customer
                    where first_name = 'MARY'
                    '''
sql_to_df(query).head()

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36.000,2011-09-14 18:10:28

In [13]:
query = '''select * from film
                    where release_year = 2006 and rating='R'
                    '''
sql_to_df(query)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,8,AIRPORT POLLOCK,A Epic Tale of a Moose And a Girl who must Con...,2006,1,None,6,4.99,54,15.99,R,Trailers,2011-09-14 18:05:33
1,17,ALONE TRIP,A Fast-Paced Character Study of a Composer And...,2006,1,None,3,0.99,82,14.99,R,"Trailers,Behind the Scenes",2011-09-14 18:05:33
2,20,AMELIE HELLFIGHTERS,A Boring Drama of a Woman And a Squirrel who m...,2006,1,None,4,4.99,79,23.99,R,"Commentaries,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:33
3,21,AMERICAN CIRCUS,A Insightful Drama of a Girl And a Astronaut w...,2006,1,None,3,4.99,129,17.99,R,"Commentaries,Behind the Scenes",2011-09-14 18:05:33
4,23,ANACONDA CONFESSIONS,A Lacklusture Display of a Dentist And a Denti...,2006,1,None,3,0.99,92,9.99,R,"Trailers,Deleted Scenes",2011-09-14 18:05:33
5,24,ANALYZE HOOSIERS,A Thoughtful Display of a Explorer And a Pastr...,2006,1,None,6,2.99,181,19.99,R,"Trailers,Behind the Scenes",2011-09-14 18:05:33
6,30,ANYTHING SAVANNAH,A Epic Story of a Pastry Chef And a Woman who ...,2006,1,None,4,2.99,82,27.99,R,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:33
7,32,APOCALYPSE FLAMINGOS,A Astounding Story of a Dog And a Squirrel who...,2006,1,None,6,4.99,119,11.99,R,"Trailers,Commentaries",2011-09-14 18:05:33
8,40,ARMY FLINTSTONES,A Boring Saga of a Database Administrator And ...,2006,1,None,4,0.99,148,22.99,R,"Trailers,Commentaries",2011-09-14 18:05:33
9,49,BADMAN DAWN,A Emotional Panorama of a Pioneer And a Compos...,2006,1,None,6,2.99,162,22.99,R,"Trailers,Commentaries,Behind the Scenes",2011-09-14 18:05:33
10,54,BANGER PINOCCHIO,A Awe-Inspiring Drama of a Car And a Pastry Ch...,2006,1,None,5,0.99,113,15.99,R,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:34
11,59,BEAR GRACELAND,A Astounding Saga of a Dog And a Boy who must ...,2006,1,None,4,2.99,160,20.99,R,Deleted Scenes,2011-09-14 18:05:34
12,60,BEAST HUNCHBACK,A Awe-Inspiring Epistle of a Student And a Squ...,2006,1,None,3,4.99,89,22.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:34
13,69,BEVERLY OUTLAW,A Fanciful Documentary of a Womanizer And a Bo...,2006,1,None,3,2.99,85,21.99,R,Trailers,2011-09-14 18:05:34
14,86,BOOGIE AMELIE,A Lacklusture Character Study of a Husband And...,2006,1,None,6,4.99,121,11.99,R,"Commentaries,Behind the Scenes",2011-09-14 18:05:34
15,90,BOULEVARD MOB,A Fateful Epistle of a Moose And a Monkey who ...,2006,1,None,3,0.99,63,11.99,R,Trailers,2011-09-14 18:05:34
16,100,BROOKLYN DESERT,A Beautiful Drama of a Dentist And a Composer ...,2006,1,None,7,4.99,161,21.99,R,Commentaries,2011-09-14 18:05:35
17,101,BROTHERHOOD BLANKET,A Fateful Character Study of a Butler And a Te...,2006,1,None,3,0.99,73,26.99,R,Behind the Scenes,2011-09-14 18:05:35
18,102,BUBBLE GROSSE,A Awe-Inspiring Panorama of a Crocodile And a ...,2006,1,None,4,4.99,60,20.99,R,"Trailers,Commentaries,Deleted Scenes,Behind th...",2011-09-14 18:05:35
19,115,CAMPUS REMEMBER,A Astounding Drama of a Crocodile And a Mad Co...,2006,1,None,5,2.99,167,27.99,R,Behind the Scenes,2011-09-14 18:05:35
20,116,CANDIDATE PERDITION,A Brilliant Epistle of a Composer And a Databa...,2006,1,None,4,2.99,70,10.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:35
21,118,CANYON STOCK,A Thoughtful Reflection of a Waitress And a Fe...,2006,1,None,7,0.99,85,26.99,R,"Trailers,Deleted Scenes",2011-09-14 18:05:35
22,129,CAUSE DATE,A Taut Tale of a Explorer And a Pastry Chef wh...,2006,1,None,3,2.99,179,16.99,R,"Commentaries,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:35
23,135,CHANCE RESURRECTION,A Astounding Story of a Forensic Psychologist ...,2006,1,None,3,2.99,70,22.99,R,"Commentaries,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:35
24,138,CHARIOTS CONSPIRACY,A Unbelieveable Epistle of a Robot And a Husba...,2006,1,None,5,2.99,71,29.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:35
25,148,CHOCOLATE DUCK,A Unbelieveable Story of a Mad Scientist And a...,2006,1,None,3,2.99,132,13.99,R,"Trailers,Commentaries,Behind the Scenes",2011-09-14 18:05:36
26,158,CLONES PINOCCHIO,A Amazing Drama of a Car And a Robot who must ...,2006,1,None,6,2.99,124,16.99,R,Behind the Scenes,2011-09-14 18:05:36
27,159,CLOSER BANG,A Unbelieveable Panorama of a Frisbee And a Hu...,2006,1,None,5,4.99,58,12.99,R,"Trailers,Behind the Scenes",2011-09-14 18:05:36
28,162,CLUELESS BUCKET,A Taut Tale of a Car And a Pioneer who must Co...,2006,1,None,4,2.99,95,13.99,R,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:36
29,168,COMANCHEROS ENEMY,A Boring Saga of a Lumberjack And a Monkey who...,2006,1,None,5,0.99,67,23.99,R,"Trailers,Behind the Scenes",2011-09-14 18:05:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,863,SUN CONFESSIONS,A Beautiful Display of a Mad Cow And a Dog who...,2006,1,None,5,0.99,141,9.99,R,"Trailers,Behind the Scenes",2011-09-14 18:05:52
166,872,SWEET BROTHERHOOD,A Unbelieveable Epistle of a Sumo Wrestler And...,2006,1,None,3,2.99,185,27.99,R,Deleted Scenes,2011-09-14 18:05:52
167,884,TERMINATOR CLUB,A Touching Story of a Crocodile And a Girl who...,2006,1,None,5,4.99,88,11.99,R,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:53
168,889,TIES HUNGER,A Insightful Saga of a Astronaut And a Explore...,2006,1,None,3,4.99,111,28.99,R,Deleted Scenes,2011-09-14 18:05:53
169,890,TIGHTS DAWN,A Thrilling Epistle of a Boat And a Secret Age...,2006,1,None,5,0.99,172,14.99,R,"Trailers,Behind the Scenes",2011-09-14 18:05:53
170,892,TITANIC BOONDOCK,A Brilliant Reflection of a Feminist And a Dog...,2006,1,None,3,4.99,104,18.99,R,"Trailers,Commentaries,Deleted Scenes,Behind th...",2011-09-14 18:05:53
171,895,TOMORROW HUSTLER,A Thoughtful Story of a Moose And a Husband wh...,2006,1,None,3,2.99,142,21.99,R,Commentaries,2011-09-14 18:05:53
172,900,TOWN ARK,A Awe-Inspiring Documentary of a Moose And a M...,2006,1,None,6,2.99,136,17.99,R,Behind the Scenes,2011-09-14 18:05:53
173,904,TRAIN BUNCH,A Thrilling Character Study of a Robot And a S...,2006,1,None,3,4.99,71,26.99,R,"Trailers,Deleted Scenes",2011-09-14 18:05:53
174,913,TROOPERS METAL,A Fanciful Drama of a Monkey And a Feminist wh...,2006,1,None,3,0.99,115,20.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:54
175,917,TUXEDO MILE,A Boring Drama of a Man And a Forensic Psychol...,2006,1,None,3,2.99,152,24.99,R,"Commentaries,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:54
176,923,UNFAITHFUL KILL,A Taut Documentary of a Waitress And a Mad Sci...,2006,1,None,7,2.99,78,12.99,R,"Commentaries,Deleted Scenes",2011-09-14 18:05:54
177,925,UNITED PILOT,A Fast-Paced Reflection of a Cat And a Mad Cow...,2006,1,None,3,0.99,164,27.99,R,"Trailers,Deleted Scenes",2011-09-14 18:05:54
178,930,VACATION BOONDOCK,A Fanciful Character Study of a Secret Agent A...,2006,1,None,4,2.99,145,23.99,R,Commentaries,2011-09-14 18:05:54
179,935,VANISHED GARDEN,A Intrepid Character Study of a Squirrel And a...,2006,1,None,5,0.99,142,17.99,R,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:54
180,938,VELVET TERMINATOR,A Lacklusture Tale of a Pastry Chef And a Tech...,2006,1,None,3,4.99,173,14.99,R,Behind the Scenes,2011-09-14 18:05:54
181,939,VERTIGO NORTHWEST,A Unbelieveable Display of a Mad Scientist And...,2006,1,None,4,2.99,90,17.99,R,"Commentaries,Behind the Scenes",2011-09-14 18:05:55
182,945,VIRGINIAN PLUTO,A Emotional Panorama of a Dentist And a Crocod...,2006,1,None,5,0.99,164,22.99,R,Deleted Scenes,2011-09-14 18:05:55
183,961,WASH HEAVENLY,A Awe-Inspiring Reflection of a Cat And a Pion...,2006,1,None,7,4.99,161,22.99,R,Commentaries,2011-09-14 18:05:55
184,967,WEEKEND PERSONAL,A Fast-Paced Documentary of a Car And a Butler...,2006,1,None,5,2.99,134,26.99,R,"Trailers,Commentaries,Deleted Scenes,Behind th...",2011-09-14 18:05:55
185,974,WILD APOLLO,A Beautiful Story of a Monkey And a Sumo Wrest...,2006,1,None,4,0.99,181,24.99,R,"Trailers,Commentaries,Deleted Scenes,Behind th...",2011-09-14 18:05:55
186,975,WILLOW TRACY,A Brilliant Panorama of a Boat And a Astronaut...,2006,1,None,6,2.99,137,22.99,R,"Trailers,Commentaries,Behind the Scenes",2011-09-14 18:05:55
187,976,WIND PHANTOM,A Touching Saga of a Madman And a Forensic Psy...,2006,1,None,6,0.99,111,12.99,R,"Commentaries,Deleted Scenes",2011-09-14 18:05:55
188,977,WINDOW SIDE,A Astounding Character Study of a Womanizer An...,2006,1,None,3,2.99,85,25.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:55
189,978,WISDOM WORKER,A Unbelieveable Saga of a Forensic Psychologis...,2006,1,None,3,0.99,98,12.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:55
190,982,WOMEN DORADO,A Insightful Documentary of a Waitress And a B...,2006,1,None,4,0.99,126,23.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:56
191,988,WORKER TARZAN,A Action-Packed Yarn of a Secret Agent And a T...,2006,1,None,7,2.99,139,26.99,R,"Trailers,Commentaries,Behind the Scenes",2011-09-14 18:05:56
192,989,WORKING MICROCOSMOS,A Stunning Epistle of a Dentist And a Dog who ...,2006,1,None,4,4.99,74,22.99,R,"Commentaries,Deleted Scenes",2011-09-14 18:05:56
193,995,YENTL IDAHO,A Amazing Display of a Robot And a Astronaut w...,2006,1,None,5,4.99,86,11.99,R,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:56
194,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,None,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2011-09-14 18:05:56

In [15]:
query = '''select * from film
                    where rating='PG' or rating='R'
                    '''
sql_to_df(query)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:32
1,6,AGENT TRUMAN,A Intrepid Panorama of a Robot And a Boy who m...,2006,1,None,3,2.99,169,17.99,PG,Deleted Scenes,2011-09-14 18:05:33
2,8,AIRPORT POLLOCK,A Epic Tale of a Moose And a Girl who must Con...,2006,1,None,6,4.99,54,15.99,R,Trailers,2011-09-14 18:05:33
3,12,ALASKA PHANTOM,A Fanciful Saga of a Hunter And a Pastry Chef ...,2006,1,None,6,0.99,136,22.99,PG,"Commentaries,Deleted Scenes",2011-09-14 18:05:33
4,13,ALI FOREVER,A Action-Packed Drama of a Dentist And a Croco...,2006,1,None,4,4.99,150,21.99,PG,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:33
5,17,ALONE TRIP,A Fast-Paced Character Study of a Composer And...,2006,1,None,3,0.99,82,14.99,R,"Trailers,Behind the Scenes",2011-09-14 18:05:33
6,19,AMADEUS HOLY,A Emotional Display of a Pioneer And a Technic...,2006,1,None,6,0.99,113,20.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:33
7,20,AMELIE HELLFIGHTERS,A Boring Drama of a Woman And a Squirrel who m...,2006,1,None,4,4.99,79,23.99,R,"Commentaries,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:33
8,21,AMERICAN CIRCUS,A Insightful Drama of a Girl And a Astronaut w...,2006,1,None,3,4.99,129,17.99,R,"Commentaries,Behind the Scenes",2011-09-14 18:05:33
9,23,ANACONDA CONFESSIONS,A Lacklusture Display of a Dentist And a Denti...,2006,1,None,3,0.99,92,9.99,R,"Trailers,Deleted Scenes",2011-09-14 18:05:33
10,24,ANALYZE HOOSIERS,A Thoughtful Display of a Explorer And a Pastr...,2006,1,None,6,2.99,181,19.99,R,"Trailers,Behind the Scenes",2011-09-14 18:05:33
11,30,ANYTHING SAVANNAH,A Epic Story of a Pastry Chef And a Woman who ...,2006,1,None,4,2.99,82,27.99,R,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:33
12,32,APOCALYPSE FLAMINGOS,A Astounding Story of a Dog And a Squirrel who...,2006,1,None,6,4.99,119,11.99,R,"Trailers,Commentaries",2011-09-14 18:05:33
13,37,ARIZONA BANG,A Brilliant Panorama of a Mad Scientist And a ...,2006,1,None,3,2.99,121,28.99,PG,"Trailers,Deleted Scenes",2011-09-14 18:05:33
14,40,ARMY FLINTSTONES,A Boring Saga of a Database Administrator And ...,2006,1,None,4,0.99,148,22.99,R,"Trailers,Commentaries",2011-09-14 18:05:33
15,41,ARSENIC INDEPENDENCE,A Fanciful Documentary of a Mad Cow And a Woma...,2006,1,None,4,0.99,137,17.99,PG,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:33
16,49,BADMAN DAWN,A Emotional Panorama of a Pioneer And a Compos...,2006,1,None,6,2.99,162,22.99,R,"Trailers,Commentaries,Behind the Scenes",2011-09-14 18:05:33
17,54,BANGER PINOCCHIO,A Awe-Inspiring Drama of a Car And a Pastry Ch...,2006,1,None,5,0.99,113,15.99,R,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:34
18,59,BEAR GRACELAND,A Astounding Saga of a Dog And a Boy who must ...,2006,1,None,4,2.99,160,20.99,R,Deleted Scenes,2011-09-14 18:05:34
19,60,BEAST HUNCHBACK,A Awe-Inspiring Epistle of a Student And a Squ...,2006,1,None,3,4.99,89,22.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:34
20,63,BEDAZZLED MARRIED,A Astounding Character Study of a Madman And a...,2006,1,None,6,0.99,73,21.99,PG,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:34
21,65,BEHAVIOR RUNAWAY,A Unbelieveable Drama of a Student And a Husba...,2006,1,None,3,4.99,100,20.99,PG,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:34
22,69,BEVERLY OUTLAW,A Fanciful Documentary of a Womanizer And a Bo...,2006,1,None,3,2.99,85,21.99,R,Trailers,2011-09-14 18:05:34
23,72,BILL OTHERS,A Stunning Saga of a Mad Scientist And a Foren...,2006,1,None,6,2.99,93,12.99,PG,"Trailers,Commentaries",2011-09-14 18:05:34
24,74,BIRCH ANTITRUST,A Fanciful Panorama of a Husband And a Pioneer...,2006,1,None,4,4.99,162,18.99,PG,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:34
25,78,BLACKOUT PRIVATE,A Intrepid Yarn of a Pastry Chef And a Mad Sci...,2006,1,None,7,2.99,85,12.99,PG,"Trailers,Deleted Scenes",2011-09-14 18:05:34
26,84,BOILED DARES,A Awe-Inspiring Story of a Waitress And a Dog ...,2006,1,None,7,4.99,102,13.99,PG,"Trailers,Commentaries",2011-09-14 18:05:34
27,86,BOOGIE AMELIE,A Lacklusture Character Study of a Husband And...,2006,1,None,6,4.99,121,11.99,R,"Commentaries,Behind the Scenes",2011-09-14 18:05:34
28,88,BORN SPINAL,A Touching Epistle of a Frisbee And a Husband ...,2006,1,None,7,4.99,179,17.99,PG,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:34
29,90,BOULEVARD MOB,A Fateful Epistle of a Moose And a Monkey who ...,2006,1,None,3,0.99,63,11.99,R,Trailers,2011-09-14 18:05:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,925,UNITED PILOT,A Fast-Paced Reflection of a Cat And a Mad Cow...,2006,1,None,3,0.99,164,27.99,R,"Trailers,Deleted Scenes",2011-09-14 18:05:54
360,928,UPTOWN YOUNG,A Fateful Documentary of a Dog And a Hunter wh...,2006,1,None,5,2.99,84,16.99,PG,Commentaries,2011-09-14 18:05:54
361,930,VACATION BOONDOCK,A Fanciful Character Study of a Secret Agent A...,2006,1,None,4,2.99,145,23.99,R,Commentaries,2011-09-14 18:05:54
362,935,VANISHED GARDEN,A Intrepid Character Study of a Squirrel And a...,2006,1,None,5,0.99,142,17.99,R,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:54
363,938,VELVET TERMINATOR,A Lacklusture Tale of a Pastry Chef And a Tech...,2006,1,None,3,4.99,173,14.99,R,Behind the Scenes,2011-09-14 18:05:54
364,939,VERTIGO NORTHWEST,A Unbelieveable Display of a Mad Scientist And...,2006,1,None,4,2.99,90,17.99,R,"Commentaries,Behind the Scenes",2011-09-14 18:05:55
365,945,VIRGINIAN PLUTO,A Emotional Panorama of a Dentist And a Crocod...,2006,1,None,5,0.99,164,22.99,R,Deleted Scenes,2011-09-14 18:05:55
366,950,VOLUME HOUSE,A Boring Tale of a Dog And a Woman who must Me...,2006,1,None,7,4.99,132,12.99,PG,Commentaries,2011-09-14 18:05:55
367,952,WAGON JAWS,A Intrepid Drama of a Moose And a Boat who mus...,2006,1,None,7,2.99,152,17.99,PG,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:55
368,955,WALLS ARTIST,A Insightful Panorama of a Teacher And a Teach...,2006,1,None,7,4.99,135,19.99,PG,"Trailers,Behind the Scenes",2011-09-14 18:05:55
369,961,WASH HEAVENLY,A Awe-Inspiring Reflection of a Cat And a Pion...,2006,1,None,7,4.99,161,22.99,R,Commentaries,2011-09-14 18:05:55
370,962,WASTELAND DIVINE,A Fanciful Story of a Database Administrator A...,2006,1,None,7,2.99,85,18.99,PG,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:55
371,963,WATCH TRACY,A Fast-Paced Yarn of a Dog And a Frisbee who m...,2006,1,None,5,0.99,78,12.99,PG,"Trailers,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:55
372,966,WEDDING APOLLO,A Action-Packed Tale of a Student And a Waitre...,2006,1,None,3,0.99,70,14.99,PG,Trailers,2011-09-14 18:05:55
373,967,WEEKEND PERSONAL,A Fast-Paced Documentary of a Car And a Butler...,2006,1,None,5,2.99,134,26.99,R,"Trailers,Commentaries,Deleted Scenes,Behind th...",2011-09-14 18:05:55
374,974,WILD APOLLO,A Beautiful Story of a Monkey And a Sumo Wrest...,2006,1,None,4,0.99,181,24.99,R,"Trailers,Commentaries,Deleted Scenes,Behind th...",2011-09-14 18:05:55
375,975,WILLOW TRACY,A Brilliant Panorama of a Boat And a Astronaut...,2006,1,None,6,2.99,137,22.99,R,"Trailers,Commentaries,Behind the Scenes",2011-09-14 18:05:55
376,976,WIND PHANTOM,A Touching Saga of a Madman And a Forensic Psy...,2006,1,None,6,0.99,111,12.99,R,"Commentaries,Deleted Scenes",2011-09-14 18:05:55
377,977,WINDOW SIDE,A Astounding Character Study of a Womanizer An...,2006,1,None,3,2.99,85,25.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:55
378,978,WISDOM WORKER,A Unbelieveable Saga of a Forensic Psychologis...,2006,1,None,3,0.99,98,12.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:55
379,980,WIZARD COLDBLOODED,A Lacklusture Display of a Robot And a Girl wh...,2006,1,None,4,4.99,75,12.99,PG,"Commentaries,Deleted Scenes,Behind the Scenes",2011-09-14 18:05:55
380,982,WOMEN DORADO,A Insightful Documentary of a Waitress And a B...,2006,1,None,4,0.99,126,23.99,R,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:56
381,983,WON DARES,A Unbelieveable Documentary of a Teacher And a...,2006,1,None,7,2.99,105,18.99,PG,Behind the Scenes,2011-09-14 18:05:56
382,985,WONDERLAND CHRISTMAS,A Awe-Inspiring Character Study of a Waitress ...,2006,1,None,4,4.99,111,19.99,PG,Commentaries,2011-09-14 18:05:56
383,987,WORDS HUNTER,A Action-Packed Reflection of a Composer And a...,2006,1,None,3,2.99,116,13.99,PG,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:56
384,988,WORKER TARZAN,A Action-Packed Yarn of a Secret Agent And a T...,2006,1,None,7,2.99,139,26.99,R,"Trailers,Commentaries,Behind the Scenes",2011-09-14 18:05:56
385,989,WORKING MICROCOSMOS,A Stunning Epistle of a Dentist And a Dog who ...,2006,1,None,4,4.99,74,22.99,R,"Commentaries,Deleted Scenes",2011-09-14 18:05:56
386,991,WORST BANGER,A Thrilling Drama of a Madman And a Dentist wh...,2006,1,None,4,2.99,185,26.99,PG,"Deleted Scenes,Behind the Scenes",2011-09-14 18:05:56
387,995,YENTL IDAHO,A Amazing Display of a Robot And a Astronaut w...,2006,1,None,5,4.99,86,11.99,R,"Trailers,Commentaries,Deleted Scenes",2011-09-14 18:05:56
388,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,None,5,2.99,101,28.99,R,"Trailers,Deleted Scenes",2011-09-14 18:05:56